In [35]:
import pandas as pd

from src.io_utils import load_data

df = load_data()
df.head()

print("Ecommerce data Information")
df.info()
print()

print("Statistics")
df.describe()
print()

print(df.isna().sum())
print()

print("Duplicates:" ,df.duplicated().sum())
print()

df["date"] = pd.to_datetime(df["date"], errors="coerce")

print("Cities:" ,list(df["city"].unique()))
print()

print("Categories:" ,list(df["category"].unique()))
print()

print("Date:" "From", df["date"] . min() , "to" ,df["date"].max())

Ecommerce data Information
<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  2500 non-null   int64
 1   date      2500 non-null   str
 2   city      2500 non-null   str
 3   category  2500 non-null   str
 4   price     2500 non-null   float64
 5   units     2500 non-null   int64
 6   revenue   2500 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 136.8 KB

Statistics

order_id    0
date        0
city        0
category    0
price       0
units       0
revenue     0
dtype: int64

Duplicates: 0

Cities: ['Stockholm', 'Malmö', 'Uppsala', 'Göteborg', 'Västerås']

Categories: ['Sports', 'Clothing', 'Home', 'Electronics', 'Toys', 'Beauty']

Date:From 2024-01-01 00:00:00 to 2024-06-30 00:00:00

In [ ]:
#Total intäkt och Antal enheter

total_intäkt = df["revenue"].sum()
antal_enheter = df["units"].sum()

#Intäkt Per Stad

from src.metrics import intäkt_per_stad

#Tabell

stads_intäkt = intäkt_per_stad(df)
stads_intäkt_tabell = stads_intäkt.reset_index()
stads_intäkt_tabell.columns = ["Stad" , "Total intäkt"]

display(stads_intäkt_tabell)
print()


högst_intäkt_stad = stads_intäkt.idxmax()
display(f"Stad med högst intäkt: {högst_intäkt_stad}")

nyckeltal_tabell = pd.DataFrame({
    "Nyckeltal": [
        "Total intäkt",
        "Totalt antal enheter",
        "Stad med högst intäkt",
       
    ],
    "Resultat": [
        total_intäkt,
        antal_enheter,
        högst_intäkt_stad,
    ]
})

display(nyckeltal_tabell)

        Stad  Total intäkt
0  Stockholm    1227201.94
1   Göteborg     859019.65
2      Malmö     567926.32
3    Uppsala     551478.42
4   Västerås     297140.90

'Stad med högst intäkt: Stockholm'

                Nyckeltal    Resultat
0            Total intäkt  3502767.23
1    Totalt antal enheter        7463
2   Stad med högst intäkt   Stockholm
3  Högsta intäkt per stad  1227201.94